{"name": "Search_NO.003_搜索失败", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "self = <test_pytest.test_allure_demo.test_allure_demo.TestSearchModel object at 0x0000029C8796B0D0>\n\n>   ???\nE   Exception: oops\n\nE:\\pytestProject\\test_allure_demo\\test_allure_demo.py:44: Exception"}, "start": 1641306488512, "stop": 1641306488512, "uuid": "263cb573-9d4f-452b-a701-312908cf202d", "historyId": "15e08dd555bbedf3036278039b7cbd74", "testCaseId": "8e93da0f31e26fa1e8e0276fa8de6f45", "fullName": "test_allure_demo.TestSearchModel#test_search_fail", "labels": [{"name": "story", "value": "搜索失败"}, {"name": "feature", "value": "搜索模块"}, {"name": "suite", "value": "test_allure_demo"}, {"name": "subSuite", "value": "TestSearchModel"}, {"name": "host", "value": "DESKTOP-5N5QG51"}, {"name": "thread", "value": "2052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_demo"}]}